<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sraavan-Sumith" ignored="0" name="Test444" tests="25" failures="6" timestamp="24 Nov 2018 03:27:38 GMT" time="0.23" errors="0">
  <testcase name="myFunction" time="0.001" classname="myTestNG.DataProviderTest"/>
  <testcase name="myFunction" time="0.005" classname="myTestNG.DataProviderTest"/>
  <testcase name="myFunction" time="0.001" classname="myTestNG.DataProviderTest"/>
  <testcase name="myFunction" time="0.0" classname="myTestNG.DataProviderTest"/>
  <testcase name="myFunction" time="0.001" classname="myTestNG.DataProviderTest"/>
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.005" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.072" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [60]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [60]
at myTestNG.CalculatorDataProviderTest.addNumbers(CalculatorDataProviderTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.002" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="addNumbers" time="0.003" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at myTestNG.CalculatorDataProviderTest.addNumbers(CalculatorDataProviderTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at myTestNG.CalculatorDataProviderTest.addNumbers(CalculatorDataProviderTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.002" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [19] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [19] but found [11]
at myTestNG.CalculatorDataProviderTest.addNumbers(CalculatorDataProviderTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [19] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [19] but found [11]
at myTestNG.CalculatorDataProviderTest.addNumbers(CalculatorDataProviderTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNumbers -->
  <testcase name="addNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="mulNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="mulNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="mulNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- mulNumbers -->
  <testcase name="mulNumbers" time="0.008" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- mulNumbers -->
  <testcase name="mulNumbers" time="0.0" classname="myTestNG.CalculatorDataProviderTest">
    <skipped/>
  </testcase> <!-- mulNumbers -->
  <testcase name="mulNumbers" time="0.001" classname="myTestNG.CalculatorDataProviderTest">
    <failure type="java.lang.AssertionError" message="MULTIPLICATION FAILED expected [36] but found [21]">
      <![CDATA[java.lang.AssertionError: MULTIPLICATION FAILED expected [36] but found [21]
at myTestNG.CalculatorDataProviderTest.mulNumbers(CalculatorDataProviderTest.java:44)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- mulNumbers -->
  <testcase name="mulNumbers" time="0.041" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="printMessage" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
  <testcase name="printMessage" time="0.001" classname="myTestNG.CalculatorDataProviderTest"/>
</testsuite> <!-- Test444 -->
